### ISSUE TITLE
Actually merge one of the 0.10.x pull requests

### ISSUE THREAD

**Issue by danopia** [pkrumins/node-jpeg#19]
I see two months-old pull reqs on this repo for 0.10.x, and since there were multiple, neither were accepted yet. I ended up setting yztaoj's fork (by random) as my project's dependency and it built and worked. Should just go ahead and pick one so I can use this library normally. :)

**Comment by pkrumins** [comment]
Hello! I merged the patch and published node-jpeg as v2.0.0.
