### ISSUE TITLE
JSON validation error in package.json

### ISSUE THREAD

**Issue by robhawkes** [pkrumins/node-jpeg#2]
package.json fails to validate in NPM and general JSON validators. The issue is down to a comma at the end of line 23 which should be deleted. Removing the comma resolves all issues.

**Comment by pkrumins** [comment]
let's see

**Comment by pkrumins** [comment]
yeah!

**Comment by pkrumins** [comment]
fixed now! thanks for the bugreport!

**Comment by pkrumins** [comment]
.
