### ISSUE TITLE
can't install the lib

### ISSUE THREAD

**Issue by sdepold** [pkrumins/node-jpeg#3]
I just downloaded the github repo and ran
    node-waf configure build
the result was the following error
    'configure' finished successfully (0.127s)
Waf: Entering directory `/Users/prototype/Projects/node-jpeg/build'
[2/7] cxx: src/jpeg_encoder.cpp -> build/default/src/jpeg_encoder_1.o
[3/7] cxx: src/jpeg.cpp -> build/default/src/jpeg_1.o
In file included from ../src/jpeg_encoder.cpp:1:
../src/jpeg_encoder.h:6:21: error: jpeglib.h: No such file or directory
../src/jpeg.cpp:3:21: error: jpeglib.h: No such file or directory

do i have to install something before?
i'm running mac os x

**Comment by pkrumins** [comment]
you're missing libjpeg headers! i don't know how software installation works on mac os x, but you should get libjpeg and make sure the include path gets passed to the compiler correctly.

**Comment by pkrumins** [comment]
closing this issue as it's ages old.
