### ISSUE TITLE
Does node-jpeg need the node_buffer.h from 0.2.*?

### ISSUE THREAD

**Issue by jim68000** [pkrumins/node-jpeg#4]
Hi, I'm trying to install image-jpeg on my node-0.3.5 system. I'm running into the problem that others have seen with:

../src/fixed_jpeg_stack.cpp:291: error: ‘class node::Buffer’ has no member named ‘data’

Looking at the source for node_buffer.h in 0.3.5 it appears there's no data() member, but there is one for 0.2.5. 

UPDATE: OK, comparing against node-png, I can see this is definitely the issue. Trying to work out how to add the buffer-compat stuff to node-jpeg.

Is this correct?

**Comment by pkrumins** [comment]
Yep, Node 3 has different API from Node 2. And only node-png has been upgraded to work with Node 2.

**Comment by mattsawyer77** [comment]
Throwing my vote in here for the fix. I'm having the same issue on node 0.4.

**Comment by pkrumins** [comment]
sorry, no time to fix it.
