### ISSUE TITLE
install failing

### ISSUE THREAD

**Issue by tmaiaroto** [pkrumins/node-jpeg#6]
Seems to be failing for me...I know Fedora 14 (and Ubuntu and many other Linux distros) are using libjpeg-turbo ... not sure if that makes a difference. 

 npm bundle install jpeg
npm info it worked if it ends with ok
npm info using npm@0.3.18
npm info using node@v0.5.0-pre
npm info preinstall jpeg@1.0.1
npm info install jpeg@1.0.1
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /home/tom/local/node 
Checking for library jpeg                : yes 
'configure' finished successfully (0.211s)
Waf: Entering directory `/home/tom/local-sites/clair/node_modules/.npm/jpeg/1.0.1/package/build'
[1/7] cxx: src/common.cpp -> build/default/src/common_1.o
[2/7] cxx: src/jpeg_encoder.cpp -> build/default/src/jpeg_encoder_1.o
[3/7] cxx: src/jpeg.cpp -> build/default/src/jpeg_1.o
[4/7] cxx: src/fixed_jpeg_stack.cpp -> build/default/src/fixed_jpeg_stack_1.o
../src/jpeg.cpp: In constructor ‘Jpeg::Jpeg(node::Buffer*, int, int, buffer_type)’:
../src/jpeg.cpp:28:42: error: ‘class node::Buffer’ has no member named ‘data’
../src/jpeg.cpp: In member function ‘v8::Handle<v8::Value> Jpeg::JpegEncodeSync()’:
../src/jpeg.cpp:44:20: error: ‘class node::Buffer’ has no member named ‘data’
../src/jpeg.cpp: In static member function ‘static int Jpeg::EIO_JpegEncodeAfter(eio_req*)’:
../src/jpeg.cpp:180:21: error: ‘class node::Buffer’ has no member named ‘data’
../src/fixed_jpeg_stack.cpp: In member function ‘v8::Handle<v8::Value> FixedJpegStack::JpegEncodeSync()’:
../src/fixed_jpeg_stack.cpp:45:24: error: ‘class node::Buffer’ has no member named ‘data’
../src/fixed_jpeg_stack.cpp: In static member function ‘static v8::Handle<v8::Value> FixedJpegStack::Push(const v8::Arguments&)’:
../src/fixed_jpeg_stack.cpp:220:43: error: ‘class node::Buffer’ has no member named ‘data’
../src/fixed_jpeg_stack.cpp: In static member function ‘static int FixedJpegStack::EIO_JpegEncodeAfter(eio_req*)’:
../src/fixed_jpeg_stack.cpp:291:21: error: ‘class node::Buffer’ has no member named ‘data’
Waf: Leaving directory`/home/tom/local-sites/clair/node_modules/.npm/jpeg/1.0.1/package/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx jpeg.cpp -> jpeg_1.o}
 -> task failed (err #1): 
    {task: cxx fixed_jpeg_stack.cpp -> fixed_jpeg_stack_1.o}
npm info jpeg@1.0.1 Failed to exec install script
npm ERR! install failed Error: jpeg@1.0.1 install: `node-waf configure build`
npm ERR! install failed `sh "-c" "node-waf configure build"` failed with 1
npm ERR! install failed     at ChildProcess.<anonymous> (/home/tom/local/node/lib/node/.npm/npm/0.3.18/package/lib/utils/exec.js:49:20)
npm ERR! install failed     at ChildProcess.emit (events.js:67:17)
npm ERR! install failed     at ChildProcess.onexit (child_process.js:192:12)
npm info install failed rollback
npm info uninstall [ 'jpeg@1.0.1' ]
npm info preuninstall jpeg@1.0.1
npm info uninstall jpeg@1.0.1
npm info auto-deactive not symlink
npm info postuninstall jpeg@1.0.1
npm info uninstall jpeg@1.0.1 complete
npm info install failed rolled back
npm ERR! Error: jpeg@1.0.1 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR!     at ChildProcess.<anonymous> (/home/tom/local/node/lib/node/.npm/npm/0.3.18/package/lib/utils/exec.js:49:20)
npm ERR!     at ChildProcess.emit (events.js:67:17)
npm ERR!     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! 
npm ERR! Failed at the jpeg@1.0.1 install script.
npm ERR! This is most likely a problem with the jpeg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls jpeg
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.35.6-45.fc14.i686
npm ERR! argv { remain: [ 'jpeg' ],
npm ERR! argv   cooked: 
npm ERR! argv    [ 'bundle',
npm ERR! argv      'install',
npm ERR! argv      'jpeg' ],
npm ERR! argv   original: 
npm ERR! argv    [ 'bundle',
npm ERR! argv      'install',
npm ERR! argv      'jpeg' ] }
npm not ok

**Comment by pkrumins** [comment]
Sorry, it only works on Node 0.2.x.
